# baseURL
@baseURL = http://localhost:3000

###
# User Signup
POST {{ baseURL }}/signup
Content-Type: application/json

{
  "username": "example1",
	"password": "password"
}

###
# User Login
POST {{ baseURL }}/login
Content-Type: application/json

{
  "username": "example2",
	"password": "password"
}

###
# User Logout
POST {{ baseURL }}/logout
Content-Type: application/json
